# ARANGE & LINSPACE

In [1]:
list(range(2,10.5,2))

TypeError: 'float' object cannot be interpreted as an integer

# Because float can not be interprete as an integer, we will use arange.

In [2]:
import numpy as np
a = np.arange(2,12.5,.3)
print(a)
a

[ 2.   2.3  2.6  2.9  3.2  3.5  3.8  4.1  4.4  4.7  5.   5.3  5.6  5.9
  6.2  6.5  6.8  7.1  7.4  7.7  8.   8.3  8.6  8.9  9.2  9.5  9.8 10.1
 10.4 10.7 11.  11.3 11.6 11.9 12.2]


array([ 2. ,  2.3,  2.6,  2.9,  3.2,  3.5,  3.8,  4.1,  4.4,  4.7,  5. ,
        5.3,  5.6,  5.9,  6.2,  6.5,  6.8,  7.1,  7.4,  7.7,  8. ,  8.3,
        8.6,  8.9,  9.2,  9.5,  9.8, 10.1, 10.4, 10.7, 11. , 11.3, 11.6,
       11.9, 12.2])

# Printing in reverse order

In [5]:
a[::-1]

array([12.2, 11.9, 11.6, 11.3, 11. , 10.7, 10.4, 10.1,  9.8,  9.5,  9.2,
        8.9,  8.6,  8.3,  8. ,  7.7,  7.4,  7.1,  6.8,  6.5,  6.2,  5.9,
        5.6,  5.3,  5. ,  4.7,  4.4,  4.1,  3.8,  3.5,  3.2,  2.9,  2.6,
        2.3,  2. ])

In [12]:
a[::-2]

array([12.2, 11.6, 11. , 10.4,  9.8,  9.2,  8.6,  8. ,  7.4,  6.8,  6.2,
        5.6,  5. ,  4.4,  3.8,  3.2,  2.6,  2. ])

In [3]:
b = np.arange(1,42,.8)
print(b)
b

[ 1.   1.8  2.6  3.4  4.2  5.   5.8  6.6  7.4  8.2  9.   9.8 10.6 11.4
 12.2 13.  13.8 14.6 15.4 16.2 17.  17.8 18.6 19.4 20.2 21.  21.8 22.6
 23.4 24.2 25.  25.8 26.6 27.4 28.2 29.  29.8 30.6 31.4 32.2 33.  33.8
 34.6 35.4 36.2 37.  37.8 38.6 39.4 40.2 41.  41.8]


array([ 1. ,  1.8,  2.6,  3.4,  4.2,  5. ,  5.8,  6.6,  7.4,  8.2,  9. ,
        9.8, 10.6, 11.4, 12.2, 13. , 13.8, 14.6, 15.4, 16.2, 17. , 17.8,
       18.6, 19.4, 20.2, 21. , 21.8, 22.6, 23.4, 24.2, 25. , 25.8, 26.6,
       27.4, 28.2, 29. , 29.8, 30.6, 31.4, 32.2, 33. , 33.8, 34.6, 35.4,
       36.2, 37. , 37.8, 38.6, 39.4, 40.2, 41. , 41.8])

# Linspace

In [13]:
l = np.linspace(2,40,5)
print(l)
l

[ 2.  11.5 21.  30.5 40. ]


array([ 2. , 11.5, 21. , 30.5, 40. ])

In [16]:
lin = np.linspace(2,100,6,endpoint=False,retstep=True)
print(lin)

(array([ 2.        , 18.33333333, 34.66666667, 51.        , 67.33333333,
       83.66666667]), 16.333333333333332)


In [17]:
lin = np.linspace(2,100,6,endpoint=True,retstep=True)
print(lin)

(array([  2. ,  21.6,  41.2,  60.8,  80.4, 100. ]), 19.6)
