# NumPy_Array

In [1]:
import numpy as np
np.array([5,6,2])

array([5, 6, 2])

In [7]:
a = np.array([5,6,2])
print(a)
a

[5 6 2]


array([5, 6, 2])

In [3]:
print(a)

[5 6 2]


In [4]:
type(a)

numpy.ndarray

In [5]:
type([5,6,2])

list

In [8]:
type(np.array([5,6,2]))

numpy.ndarray

# Two Dimensional Array

In [11]:
arr = np.array([[1,2],[4,5]])
print(arr)
arr

[[1 2]
 [4 5]]


array([[1, 2],
       [4, 5]])

In [16]:
print("Data_type-", arr.dtype)
print("\n",arr)

Data_type- int32

 [[1 2]
 [4 5]]


In [17]:
arr1 = np.array([[0,9],[1,2],[4,5]])
print(arr1)
arr1

[[0 9]
 [1 2]
 [4 5]]


array([[0, 9],
       [1, 2],
       [4, 5]])

In [20]:
np.array([[0,9],[1,2],[4,5]])

array([[0, 9],
       [1, 2],
       [4, 5]])

# Create array using .mat(Matrix)

In [24]:
arr2 = np.array(np.mat("123;908"))
print(arr2)
arr2

[[123]
 [908]]


array([[123],
       [908]])

In [25]:
arr3 = np.array(np.mat("543;873;4322"))
print(arr3)

[[ 543]
 [ 873]
 [4322]]


# Convert a list into an array

In [50]:
list_1 = [1,2,3,4,5]
arr4 = np.array(list_1)
print(arr4)

l = [[1,2,3,3],[4,3,2,4]]
arr_4 = np.array(l)
print(arr_4)

[1 2 3 4 5]
[[1 2 3 3]
 [4 3 2 4]]


In [48]:
arr5 = np.array(np.mat(list_1))
arr_5 = np.array(np.mat(l))
print(arr_5)
print(arr5)

[[1 2 3 3]
 [4 3 2 4]]
[[1 2 3 4 5]]


In [33]:
list_2 = np.array(np.mat("123;345;654"))
print(list_2)
list_2

[[123]
 [345]
 [654]]


array([[123],
       [345],
       [654]])

In [34]:
arr6 = np.array(np.mat(list_2))
print(arr6)
arr6

[[123]
 [345]
 [654]]


array([[123],
       [345],
       [654]])

# Copy an array in other array

In [35]:
arr7 = np.asarray(arr6)
print(arr7)
arr7

[[123]
 [345]
 [654]]


array([[123],
       [345],
       [654]])

# NumPy_Data Type

In [51]:
data_type1 = [[1,2,3.5],[3,4,5],[5,6,7]]
data = np.array(data_type1)
print(data)

[[1.  2.  3.5]
 [3.  4.  5. ]
 [5.  6.  7. ]]


In [64]:
data_type = [[1,2,3],[3,4,5],[5,6,7]]
data = np.array(data_type)
print("The Matric is \n ----------- \n",data,"\n------------\n")
print("type/class of this object-", type(data))
print("The dimension of the Metrix is :", data.ndim)
print("The size of the Matrix is:", data.size)
print("The shape of the Matrix is:", data.shape)
print("The data type of the Matrix is:", data.dtype)

The Matric is 
 ----------- 
 [[1 2 3]
 [3 4 5]
 [5 6 7]] 
------------

type/class of this object- <class 'numpy.ndarray'>
The dimension of the Metrix is : 2
The size of the Matrix is: 9
The shape of the Matrix is: (3, 3)
The data type of the Matrix is: int32
